### ISSUE TITLE
Language  Error

### ISSUE THREAD

**Issue by avvam** [pierre-vassoilles/recaptcha-bundle#1]
There is an error in language suport in https://github.com/pierre-vassoilles/recaptcha-bundle/blob/master/Pv/RecaptchaBundle/Resources/views/Form/recaptcha_widget.html.twig file. 
You used `lang` parameter. It is not work. Parameter must be `hl`.

**Comment by pierre-vassoilles** [comment]
Hi !
The issue was fixed, thank you @avvam for the report ;)

Have a nice day !
